version: "2"
services:
  google_dyn_dns:
    image: henryse/google_dyn_dns:latest
    ports:
      - "8443:443"
    environment:
      - "HOST=$DOCKER_IP"
      - "LOGSTASH_ENABLED=false"
      - "SERVICE_NAME=google_dyn_dns"
      - "SERVICE_443_CHECK_HTTPS=/health"
      - "SERVICE_TAGS=traefik.enable=true"

  registrator:
    image: gliderlabs/registrator:v7
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: -ip $DOCKER_IP consul://router.applegate.farm:8500
    network_mode: host
    logging:
      driver: none
